apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
spec:
  type: NodePort
  # type: LoadBalancer  # Expose Mongo Express externally
  ports:
    - port: 8081  # Expose port 8081 to the outside world
      targetPort: 8081  # The port Mongo Express listens on
      nodePort: 30002
      protocol: TCP
  selector:
    app: mongo-express  # Select Mongo Express pods
