apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-test
spec:
  selector:
    app: mongodb
  clusterIP: None  # Headless service for StatefulSet
  ports:
    - protocol: TCP
      port: 27017  # Exposing port 27017
      targetPort: 27017  # Port on the MongoDB pod

