apiVersion: v1
kind: Pod
metadata:
  name: pvc-debugger
spec:
  containers:
  - name: debugger
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: backup-storage
      mountPath: /backup
  volumes:
  - name: backup-storage
    persistentVolumeClaim:
      claimName: mongodb-backup-pvc  # Same PVC used for backup
  restartPolicy: Never
